ServerSoftware        server-http3
ServerAddr            0.0.0.0
ServerPort	      4433

DocumentRoot	      ../../www/html
ScriptDir             ../../www/cgi
LogDir                logs

Certificate	     certs/cert.pem
CertificateKey	     certs/key.pem

####### UsePHP: off, php-fpm, php-cgi #######
UsePHP                php-cgi
#PathPHP               127.0.0.1:9000  # [php-fpm: 127.0.0.1:9000 (/var/run/php-fpm.sock)], [php-cgi: /usr/bin/php-cgi]
PathPHP               /usr/bin/php-cgi 

MaxAcceptConnections  1000
MaxStreams            150

ServerNameIndication  on

TimeOut               15

TimeoutCGI            5
MaxCgiProc            10

ShowMediaFiles        on

scgi {
	~/scgi_test 127.0.0.1:9009
}
