ServerSoftware        server-http3
ServerAddr            0.0.0.0
ServerPort	      4433

DocumentRoot	      ../../www/html
ScriptDir             ../../www/cgi
LogDir                logs

Certificate	     certs/cert.pem
CertificateKey	     certs/key.pem

####### UsePHP: off, php-fpm, php-cgi #######
UsePHP                php-fpm
PathPHP               127.0.0.1:9000  # [php-fpm: 127.0.0.1:9000 (/var/run/php-fpm.sock)], [php-cgi: /usr/bin/php-cgi]
#PathPHP               /usr/bin/php-cgi 

MaxAcceptConnections  1000
MaxWorkStreams        150

ServerNameIndication  on

TimeOut               15

TimeoutCGI            5
MaxCgiProc            10

ShowMediaFiles        on

fastcgi {
        ~/env  127.0.0.1:9002

	~/fcgi_test  127.0.0.1:9002

        /perl/env.pl 127.0.0.1:9003
        /env.pl 127.0.0.1:9003
        
        /python/env.py 127.0.0.1:9003
        /env.py 127.0.0.1:9003
        
        /python/submit.py 127.0.0.1:9003
        /submit.py 127.0.0.1:9003
        
        /script 127.0.0.1:9003

        /upload-fcgi  127.0.0.1:9020
        /sensors      192.168.100.136:9011
}

scgi {
	~/scgi_test 127.0.0.1:9009
}
